import os
from collections.abc import Iterable
from typing import Final

# bytes, bytearray, memoryview or any other C-contiguous buffer (str must be encoded first)
Buffer = bytes | bytearray | memoryview
StrPath = str | os.PathLike[str]
# "sha256" or "blake3" (any letter case; "sha-256" is also accepted)
AlgorithmName = str

ALGORITHMS: Final[tuple[str, str]]
DIGEST_SIZE: Final[int]

class Digest:
    """A 32-byte digest, tagged with the algorithm that produced it. `str()` gives lowercase hex."""

    @staticmethod
    def from_hex(algorithm: AlgorithmName, hex: str) -> Digest: ...
    @property
    def algorithm(self) -> str: ...
    @property
    def digest_size(self) -> int: ...
    def digest(self) -> bytes: ...
    def hexdigest(self) -> str: ...
    def hex(self) -> str: ...
    def __bytes__(self) -> bytes: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class Hasher:
    """An incremental hasher, like hashlib.sha256()."""

    def __init__(self, algorithm: AlgorithmName = "sha256", data: Buffer | None = None) -> None: ...
    def update(self, data: Buffer) -> None: ...
    def update_file(self, path: StrPath) -> int: ...
    def finalize(self) -> Digest: ...
    def digest(self) -> bytes: ...
    def hexdigest(self) -> str: ...
    def copy(self) -> Hasher: ...
    def reset(self) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def digest_size(self) -> int: ...

def hash_bytes(algorithm: AlgorithmName, data: Buffer) -> Digest: ...
def hash_file(algorithm: AlgorithmName, path: StrPath) -> Digest: ...
def hash_files(algorithm: AlgorithmName, paths: Iterable[StrPath]) -> list[Digest]: ...
