from collections.abc import Iterable

Item = bytes | bytearray | str

class MinHasher:
    """The permutation functions. Build once and reuse for every document."""

    def __init__(self, num_perm: int = 128, seed: int = 1) -> None: ...
    @property
    def num_perm(self) -> int: ...
    @property
    def permutations(self) -> tuple[list[int], list[int]]: ...
    def empty(self) -> Signature: ...
    def signature(self, items: Iterable[Item]) -> Signature: ...
    def signatures(self, documents: Iterable[Iterable[Item]]) -> list[Signature]: ...

class Signature:
    """A MinHash signature."""

    def update(self, hasher: MinHasher, item: Item) -> None: ...
    def update_batch(self, hasher: MinHasher, items: Iterable[Item]) -> None: ...
    def jaccard(self, other: Signature) -> float: ...
    def merge(self, other: Signature) -> None: ...
    @property
    def values(self) -> list[int]: ...
    @property
    def hashvalues(self) -> list[int]: ...
    def copy(self) -> Signature: ...
    def __len__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
